; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define GTKPATH "C:\msys64\mingw64\"
#define SITE "https://slovesnov.rf.gd"
#define APPNAME "bridge"
#define VERSION "5.3.1"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E7506159-838C-471E-A941-ECAFF1EB6EC0}
AppName={#APPNAME}
AppVersion={#VERSION}
AppPublisher=Alexey Slovesnov
AppPublisherURL={#SITE}?{#APPNAME}
AppSupportURL={#SITE}?{#APPNAME}
AppUpdatesURL={#SITE}?{#APPNAME}
DefaultDirName={commonpf}\{#APPNAME}
;user can select setup folder
DisableDirPage=no
DefaultGroupName={#APPNAME}
OutputBaseFilename={#APPNAME}{#VERSION}Setup
SetupIconFile={#APPNAME}\icon\app.ico
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes

[REGISTRY]
Root: HKCR; Subkey: ".bts"; ValueType: string; ValueName: ""; ValueData: "BridgeStudio"; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".pts"; ValueType: string; ValueName: ""; ValueData: "BridgeStudio"; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".pbn"; ValueType: string; ValueName: ""; ValueData: "BridgeStudio"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "BridgeStudio"; ValueType: string; ValueName: ""; ValueData: "BridgeStudio"; Flags: uninsdeletekey
Root: HKCR; Subkey: "BridgeStudio\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\bridge.exe,0"
Root: HKCR; Subkey: "BridgeStudio\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\bridge.exe"" ""%1"""


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Messages]
english.BeveledLabel=English
russian.BeveledLabel=Russian
italian.BeveledLabel=Italian

[InstallDelete]

[Files]
;pan-up-symbolic.symbolic.png, pan-down-symbolic.symbolic.png Arrow up/down. It's combobox arrow
;pan-end-symbolic.symbolic.png right arrow for menu
;list-add-symbolic.symbolic.png list-remove-symbolic.symbolic.png +/- for "font selection"
;edit-find-symbolic.symbolic.png "search image" for "font selection"
;for select font option {list-add-symbolic.symbolic.png list-remove-symbolic.symbolic.png edit-find-symbolic.symbolic.png
;spinner process-working-symbolic.svg
;BEGIN file open
;Adwaita\16x16\ different folder
;Adwaita\index.theme
;for russian char need use share/locale/ 54mb. Even share/locale/ru 2mb too big folder
;END file open 
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\ui\pan-up-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\ui\pan-down-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\ui\pan-end-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\actions\list-add-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\actions\list-remove-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
;Source: "{#GTKPATH}share\icons\Adwaita\16x16\actions\edit-find-symbolic.symbolic.png"; DestDir: "{app}\share\icons\Adwaita\16x16\actions"; Flags: onlyifdoesntexist
Source: "{#GTKPATH}share\icons\Adwaita\16x16\*"; DestDir: "{app}\share\icons\Adwaita\16x16"; Flags: onlyifdoesntexist recursesubdirs
Source: "{#GTKPATH}share\icons\Adwaita\index.theme"; DestDir: "{app}\share\icons\Adwaita"; Flags: ignoreversion
;5.3.1 it's seems not need
;Source: "{#GTKPATH}share\icons\Adwaita\symbolic\ui\process-working-symbolic.svg"; DestDir: "{app}\share\icons\Adwaita\symbolic\ui"; Flags: ignoreversion

;Source: "{#GTKPATH}share\icons\Adwaita\symbolic-up-to-32\status\process-working-symbolic.svg"; DestDir: "{app}\share\icons\Adwaita\symbolic-up-to-32\status"; Flags: onlyifdoesntexist

#define i

#dim Files[57]
#define Files[0] "libLerc"
#define Files[1] "libatk-1.0-0"
#define Files[2] "libbrotlicommon"
#define Files[3] "libbrotlidec"
#define Files[4] "libbz2-1"
#define Files[5] "libcairo-2"
#define Files[6] "libcairo-gobject-2"
#define Files[7] "libcrypto-3-x64"
#define Files[8] "libcurl-4"
#define Files[9] "libdatrie-1"
#define Files[10] "libdeflate"
#define Files[11] "libepoxy-0"
#define Files[12] "libexpat-1"
#define Files[13] "libffi-8"
#define Files[14] "libfontconfig-1"
#define Files[15] "libfreetype-6"
#define Files[16] "libfribidi-0"
#define Files[17] "libgcc_s_seh-1"
#define Files[18] "libgdk-3-0"
#define Files[19] "libgdk_pixbuf-2.0-0"
#define Files[20] "libgio-2.0-0"
#define Files[21] "libglib-2.0-0"
#define Files[22] "libgmodule-2.0-0"
#define Files[23] "libgobject-2.0-0"
#define Files[24] "libgraphite2"
#define Files[25] "libgtk-3-0"
#define Files[26] "libharfbuzz-0"
#define Files[27] "libiconv-2"
#define Files[28] "libidn2-0"
#define Files[29] "libintl-8"
#define Files[30] "libjbig-0"
#define Files[31] "libjpeg-8"
#define Files[32] "liblzma-5"
#define Files[33] "libminizip-ng-1"
#define Files[34] "libnghttp2-14"
#define Files[35] "libnghttp3-9"
#define Files[36] "libngtcp2-16"
#define Files[37] "libngtcp2_crypto_ossl-0"
#define Files[38] "libpango-1.0-0"
#define Files[39] "libpangocairo-1.0-0"
#define Files[40] "libpangoft2-1.0-0"
#define Files[41] "libpangowin32-1.0-0"
#define Files[42] "libpcre2-8-0"
#define Files[43] "libpixman-1-0"
#define Files[44] "libpng16-16"
#define Files[45] "libpsl-5"
#define Files[46] "libsharpyuv-0"
#define Files[47] "libssh2-1"
#define Files[48] "libssl-3-x64"
#define Files[49] "libstdc++-6"
#define Files[50] "libthai-0"
#define Files[51] "libtiff-6"
#define Files[52] "libunistring-5"
#define Files[53] "libwebp-7"
#define Files[54] "libwinpthread-1"
#define Files[55] "libzstd"
#define Files[56] "zlib1"

#sub FilesEntry
Source: "{#GTKPATH}bin\{#Files[i]}.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
#endsub
#for {i = 0; i < DimOf(Files); i++} FilesEntry

Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders.cache"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0"; Flags: ignoreversion
Source: "{#GTKPATH}lib\gdk-pixbuf-2.0\2.10.0\loaders\*.dll"; DestDir: "{app}\lib\gdk-pixbuf-2.0\2.10.0\loaders"; Flags: ignoreversion
Source: "{#GTKPATH}share\glib-2.0\schemas\gschemas.compiled"; DestDir: "{app}\share\glib-2.0\schemas"; Flags: ignoreversion

Source: "{#APPNAME}.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "*.css"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#APPNAME}\images\*"; Excludes: "*.txt"; DestDir: "{app}\bin\{#APPNAME}\images"; Flags: ignoreversion
Source: "{#APPNAME}\lng\*"; DestDir: "{app}\bin\{#APPNAME}\lng"; Flags: ignoreversion
Source: "{#APPNAME}\problems\*";  DestDir: "{app}\bin\problems"; Flags: onlyifdoesntexist
Source: "{#APPNAME}\problems\bts\*";  DestDir: "{app}\bin\problems\bts"; Flags: onlyifdoesntexist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{commondesktop}\{#APPNAME}"; Filename: "{app}\bin\{#APPNAME}.exe"
Name: "{group}\{cm:UninstallProgram,{#APPNAME}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\bin\{#APPNAME}.exe"; Description: "{cm:LaunchProgram,{#APPNAME}}"; Flags: nowait postinstall skipifsilent

[Code]
//procedure CurStepChanged(CurStep: TSetupStep);
//begin
//  Log('CurStepChanged(' + IntToStr(Ord(CurStep)) + ') called');
//  if CurStep = ssInstall then
//    DeleteFile(ExpandConstant('{app}\*.*'));
//end;
// DelTree('C:\Test\*.tmp', False, True, False);
